name: Firmware Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: latest
        target: esp32s3
        path: '.'

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: |
          build/bootloader/bootloader.bin
          build/partition_table/partition-table.bin
          build/gamepad-gateway-usb2ble.bin
          build/gamepad-gateway-usb2ble.elf
          build/flasher_args.json
